// Builds src/styles/vendor.css (regular pages) and src/styles/vendor-lp.css
// (LearnPress pages) from the live site's stylesheet load order, and extracts
// the per-page inline CSS block that only some pages carry.
import fs from 'fs';
import path from 'path';
const A = process.argv[2];
const read = (f) => fs.readFileSync(f, 'utf8');
const V = 'src/styles/vendor/';
const exists = (p) => fs.existsSync(path.join(V, p));
const link = (p) => (exists(p) ? `@import './vendor/${p}';` : `/* missing on the live site (HTTP 404): ${p} */`);
const inline = (n) => `@import './inline/${n}';`;
const PER_PAGE_POST = /post-(11|144|146|148|150|152|154|156|158|2271)\.css$/;

function build(orderFile, lpPage) {
  const order = read(orderFile).split(/\r?\n/).filter(Boolean);
  const out = [`/* Stylesheets of the current site in their exact load order (${path.basename(orderFile)}). Generated by scripts/gen-css.mjs */`];
  // inline style blocks, in order of appearance on that page type
  const noids = lpPage ? ['06-noid.css', '07-noid.css', '09-noid.css'] : ['06-noid.css', '07-noid.css', '09-noid.css'];
  let noid = 0;
  for (const o of order) {
    if (o.startsWith('LINK ')) {
      const p = o.slice(5);
      if (/fonts\.googleapis/.test(p)) continue; // Google Fonts are linked from index.html
      if (p.endsWith('post-1844.css')) { out.push('/* post-1844.css is missing (HTTP 404) on the live site, so it is intentionally not loaded here either */'); continue; }
      if (PER_PAGE_POST.test(p)) continue; // loaded per page (src/styles/elementor)
      out.push(link(p));
    } else {
      const id = o.slice(6);
      if (id === '(noid)') { const n = noids[noid++]; if (n) out.push(inline(n)); continue; }
      const file = fs.readdirSync('src/styles/inline').find((f) => f.endsWith('-' + id + '.css'));
      if (file) out.push(inline(file));
    }
  }
  return out.join('\n') + '\n';
}
fs.writeFileSync('src/styles/vendor.css', build(path.join(A, 'css-order-home.txt'), false));
fs.writeFileSync('src/styles/vendor-lp.css', build(path.join(A, 'css-order-course.txt'), true));

// Per-page inline CSS (theme page options: content padding), keyed by path
const dec = (s) => s.replace(/&#038;/g, '&');
const pages = {};
const dirs = ['pages', 'extra', 'testimonials', 'categories', 'courses'];
for (const d of dirs) {
  const dir = path.join(A, d);
  if (!fs.existsSync(dir)) continue;
  for (const f of fs.readdirSync(dir)) {
    const t = read(path.join(dir, f));
    const m = t.match(/<style[^>]*>\s*(\.main-contain #content,\s*body\.rs-pages-btm-gap[\s\S]*?)<\/style>/);
    if (!m) continue;
    const canonical = (t.match(/<link rel="canonical" href="([^"]+)"/) || [])[1];
    const key = canonical ? new URL(canonical).pathname : null;
    if (!key) continue;
    pages[key === '/courses__trashed/hadoop/' ? '/hadoop/' : key] = dec(m[1]).replace(/\s+/g, ' ').trim();
  }
}
fs.writeFileSync('src/data/page-inline-css.json', JSON.stringify(pages, null, 0));
console.log('vendor.css lines:', fs.readFileSync('src/styles/vendor.css', 'utf8').split('\n').length, '| vendor-lp.css lines:', fs.readFileSync('src/styles/vendor-lp.css', 'utf8').split('\n').length);
console.log('pages with inline padding css:', Object.keys(pages).length, JSON.stringify(pages['/'] || ''), JSON.stringify(pages['/contact/'] || ''));
